version: "3.9"
services:
  database:
    image: ${APP_NAME}_database
    build:
      context: ./database
    container_name: ${APP_NAME}_database
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - common

  client:
    image: ${APP_NAME}_client
    build:
      context: ./client
    container_name: ${APP_NAME}_client
    command: pnpm prod
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - common

  server:
    image: ${APP_NAME}_server
    build:
      context: ./server
    container_name: ${APP_NAME}_server
    command: composer run-script start-prod
    restart: unless-stopped
    ports:
      - 4200:4200
    depends_on:
      - database
    networks:
      - common

  nginx:
    image: ${APP_NAME}_nginx
    build:
      context: ./nginx
    container_name: ${APP_NAME}_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - server
      - client
    networks:
      - common

  mailer:
    image: ${APP_NAME}_mailer
    build:
      context: ./mailer
    container_name: ${APP_NAME}_mailer
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    depends_on:
      - server
    networks:
      - common

networks:
  common:
    name: ${APP_NAME}_network
    driver: bridge
