version: "3.9"
services:
  database:
    environment:
      - POSTGRES_USER=${LOCAL_DB_USER}
      - POSTGRES_PASSWORD=${LOCAL_DB_PASSWORD}
      - POSTGRES_DB=${LOCAL_DB_NAME}

  client:
    command: pnpm dev
    stdin_open: true
    tty: true
    ports:
      - 3001:3000
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/public:/usr/src/app/public
      - ./client/index.html:/usr/src/app/index.html
      - ./client/package.json:/usr/src/app/package.json

  server:
    command: composer run-script start-local
    volumes:
      - ./server/app:/usr/src/app/app
      - ./server/bootstrap:/usr/src/app/bootstrap
      - ./server/config:/usr/src/app/config
      - ./server/database:/usr/src/app/database
      - ./server/public:/usr/src/app/public
      - ./server/routes:/usr/src/app/routes
      - ./server/storage:/usr/src/app/storage
      - ./server/tests:/usr/src/app/tests
      - ./server/composer.json:/usr/src/app/composer.json

  nginx:
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/nginx.conf

  storage:
    command: pnpm local
    volumes:
      - ./storage/src:/usr/src/app/src
      - ./storage/public:/usr/src/app/public
      - ./storage/dist:/usr/src/app/dist
