version: "3.9"
services:
  database:
    image: ${APP_NAME}_database
    build:
      context: ./database
    container_name: ${APP_NAME}_database
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - common

  client:
    image: ${APP_NAME}_client
    build:
      context: ./client
    container_name: ${APP_NAME}_client
    command: pnpm prod
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - API_HOST=http://server:4200
    networks:
      - common

  server:
    image: ${APP_NAME}_server
    build:
      context: ./server
    container_name: ${APP_NAME}_server
    command: php artisan serve --host 0.0.0.0
    restart: unless-stopped
    ports:
      - 4200:4200
    environment:
      - APP_NAME=${APP_NAME}
      - ENV=production
      - DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_PORT=5432
      - DB_HOST=database
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - database
    networks:
      - common

  nginx:
    image: ${APP_NAME}_nginx
    build:
      context: ./nginx
    container_name: ${APP_NAME}_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - server
      - client
    networks:
      - common

networks:
  common:
    name: ${APP_NAME}_network
    driver: bridge
