version: "3.9"
services:
  client:
    command: pnpm dev
    stdin_open: true
    tty: true
    volumes:
      - ./client/app:/usr/src/app/app

  server:
    command: php artisan serve --host 0.0.0.0
    environment:
      - APP_NAME=${APP_NAME}
      - ENV=development
      - DEBUG=true
    volumes:
      - ./server:/usr/src/app

  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/nginx.conf
