version: "3.9"
services:
  client:
    command: pnpm dev
    stdin_open: true
    tty: true
    ports:
      - 3001:3000
    volumes:
      - ./client/src:/usr/src/app/src

  server:
    command: php artisan serve --host 0.0.0.0
    environment:
      - APP_NAME=${APP_NAME}
      - ENV=development
      - DEBUG=true
    volumes:
      - ./server:/usr/src/app

  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/nginx.conf
