version: "3.9"
services:
  client:
    image: ${APP_NAME}_client
    build:
      context: ./client
    container_name: ${APP_NAME}_client
    command: pnpm prod
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - common

  server:
    image: ${APP_NAME}_server
    build:
      context: ./server
    container_name: ${APP_NAME}_server
    command: php artisan serve --host 0.0.0.0
    restart: unless-stopped
    ports:
      - 4200:4200
    environment:
      - APP_NAME=${APP_NAME}
      - ENV=production
      - DEBUG=false
    networks:
      - common

  nginx:
    image: ${APP_NAME}_nginx
    build:
      context: ./nginx
    container_name: ${APP_NAME}_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - server
      - client
    networks:
      - common

networks:
  common:
    name: ${APP_NAME}_network
    driver: bridge
